_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 55
            "4": 3.10.13
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
input_artifact:
    value: exercise_14/raw_data_v2.parquet:latest
output_artifact:
    value: clean_data.parquet
output_description:
    value: Cleaned dataset after dropping columns
output_type:
    value: cleaned_data
