_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.13
        t:
            "3":
                - 55
            "4": 3.10.13
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
