channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - packaging==24.2
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.5.1
  - scipy==1.14.1
name: mlflow-env
